### ISSUE TITLE
Documentation glitch

### ISSUE THREAD

**Issue by chymian** [arminus/ObsidianReceiver#5]
in the docu, there is the configpath `config/Couchdb.conf` referred, and `obsidian_config/Couchdb.conf` in the docker cmd line.
whats true?

> ## Configuring the Obsidian/CouchDB parameters
> Set the appropriate values in **config**/CouchDB.yaml

docker run -d --name obsreceiver --env SERVER_PORT=$OBS_SERVER_PORT -p $OBS_SERVER_PORT:$OBS_SERVER_PORT \
-v /$(pwd)/**obsidian_conf**:/root/**obsidian_conf** obsreceiver:latest

I assume the later is correct.

**Comment by arminus** [comment]
Yes obsidian_conf, fixed that accordingly.
